### PR TITLE
Screen break points on about section

### PR DESCRIPTION
**Pull request by ikayz**
Added classes for extra small, small, medium, large, and extra on about section.

### CODE REVIEW

**Comment by OlivierJM** [comment]
Heyyy @ikayz it looks like the build is failing, I will investigating this before merging it.

**Comment by ikayz** [comment]
Package-lock there is a library I use and when merging it added those strings. Lemme remove them and see make a pull request with other minor tweaks.

**Comment by OlivierJM** [comment]
Is it the `npx npm-merge-driver` ?

Actually what you can do is you can remove the eslint config and its plugin for now, unless if you think it is really needed. 
but let me know what is easy on your side

**Comment by ikayz** [comment]
I just use it on my local environment it's not for everyone. I've ignored it's config file and removed it.

**Comment by OlivierJM** [comment]
cool, push those changes on this branch to see if the build can pass.

**Comment by ikayz** [comment]
Okay, the colour palette is gone from the directory. I want a certain colour from it. Want to make the small changes and push together.

**Comment by OlivierJM** [comment]
alright no problem

**Comment by OlivierJM** [comment]
This is passing thanks for this, let me check it

**Comment by OlivierJM** [comment]
@allcontributors please add @ikayz for code

**Comment by ikayz** [comment]
Cool, more tweaks will be added as I discover them.

**Comment by OlivierJM** [comment]
Alright, I will merge this for now, thanks.

**Pull request merged**
