### PR TITLE
WIP: Add checks

### LINKED ISSUE #157: [Proposal] set up more checks
To keep the repo healthy and more maintainable we need to go beyond guidelines and emphasize on what gets through to master branch. 
we can set up different continuous tools to make sure all the checks are passed beyond the project building and deploying, 

some examples are:

- Github Actions
- [Buddy.works](https://buddy.works/)
- Travis CI or any CI 

**Checks we can emphasize**

- Repo size
- Image optimizations
- Code quality
- Linting

### PR DESCRIPTION
**Pull request by OlivierJM**
Fixes #157 
Pull requests will be checked by buddy.works, travis and lgtm.
All commits will also be auto cleaned to keep the code clean.

### CODE REVIEW

**Comment by OlivierJM** [comment]
This PR is just for a proper set up more will be coming early

**Comment by k9uma** [comment]
> 
> 
> This PR is just for a proper set up more will be coming early

Okay great, whats causing the build to fail the Travis tests?

**Comment by OlivierJM** [comment]
> > This PR is just for a proper set up more will be coming early
> 
> Okay great, whats causing the build to fail the Travis tests?

It's failing to build because of some errors in the codebase, you can check the logs here https://travis-ci.com/devconzm/devconzm/builds/140749388

Any warnings that is generated in the build process is reported as an error in CI environment

**Comment by OlivierJM** [comment]
> > > This PR is just for a proper set up more will be coming early
> > 
> > 
> > Okay great, whats causing the build to fail the Travis tests?
> 
> It's failing to build because of some errors in the codebase, you can check the logs here https://travis-ci.com/devconzm/devconzm/builds/140749388
> 
> Any warnings that is generated in the build process is reported as an error in CI environment

**Comment by OlivierJM** [comment]
Sorry I accidentally closed this 🤦🏾‍♂️

**Comment by k9uma** [comment]
> 
> 
> Sorry I accidentally closed this 🤦🏾‍♂️

Can we go ahead and merge this PR...?

**Comment by OlivierJM** [comment]
Let me push for that fix then we merge it. give few minutes

**Comment by OlivierJM** [comment]
we are good now.

**Pull request merged**
