### PR TITLE
Revert "Speaker details feature"

### PR DESCRIPTION
**Pull request by malgamves**

### CODE REVIEW

**Comment by OlivierJM** [comment]
taking a look at this now

**Comment by malgamves** [comment]
Yes, because the build failed

**Comment by OlivierJM** [comment]
@malgamves I have restricted the branches a little harder to make sure we avoid mistakes of merging when things aren't okay, it's super dangerous.
Review them here and add the ones you think need to be added 
https://github.com/devconzm/devconzm/settings/branch_protection_rules/5797139

**Comment by malgamves** [comment]
Agreed! Happy with the changes

**Comment by OlivierJM** [comment]
Should I merge this ?

**Comment by malgamves** [comment]
Yes please

**Comment by OlivierJM** [comment]
done

**Pull request merged**
