### PR TITLE
Setup router[WIP]

### PR DESCRIPTION
**Pull request by OlivierJM**
I have set up an initial router components

- Speakers on their own page
- CoC on its own page

**What needs to be done**
- Change the navbar links to NavLink(Component from react-router-dom)
or
- Fix the styling to match the new links

### CODE REVIEW

**Comment by OlivierJM** [comment]
Bad practice 🤦🏾‍♂️

- Used a history.push() with an anchor
- PR not completed

The above is just to show the current router working but because of anchor tags it will break other links in the header.
As suggested above, we need to change the links in the header to use either <Link> or <NavLink> NavLink is best since it can be custom styled to detect the current route and change the active link.

**Comment by OlivierJM** [comment]
Another thing, I just noticed is that Netlify is acting up on the route surprisingly

**To do**

Help find what is causing this

**Comment by OlivierJM** [comment]
> Another thing, I just noticed is that Netlify is acting up on the route surprisingly
> 
> **To do**
> 
> Help find what is causing this

This seems to be working in this PR.

**Comment by OlivierJM** [comment]
I fixed the issues mentioned above

@malgamves I need help on setting proper styles in navlinks, somethings seem to not coordinate well, especially on active route.

**Comment by malgamves** [comment]
Checking it out @OlivierJM

**Pull request merged**
