### PR TITLE
Schedule debug

### PR DESCRIPTION
**Pull request by malgamves**
Seeing if schedule shows in build

### CODE REVIEW

**Comment by OlivierJM** [comment]
Hi @malgamves, I think we can update the json to make sure it contains the right information from the schedule and it should be able to pick it automatically then we can also add a header on the schedule page.
Can we share the PR and the issue to see if we can get some contributors on this ?

**Comment by malgamves** [comment]
Sure

**Comment by malgamves** [comment]
@OlivierJM or @Beardless-sheik can we fix the styling here?

**Comment by OlivierJM** [comment]
let me take a look, it seems like there is some conflicts ,is that the only problem ?

**Comment by malgamves** [comment]
Ok please

*Daniel Madalitso Phiri*
malgamves.dev

**Comment by OlivierJM** [comment]
I think what's remaining is just updating the timing and maybe add some styling.

**Pull request closed without merging**
