### PR TITLE
Fixed responsiviness issue on small screen

### PR DESCRIPTION
**Pull request by Chizzoz**
Made image assets fluid and columns stack in small screen mode

### CODE REVIEW

**Comment by OlivierJM** [comment]
awesome let me check it out.

**Comment by Chizzoz** [comment]
Decided to make the purple image in header smaller to accommodate collapsing menu

**Comment by OlivierJM** [comment]
The contact us in the menu seems to break to the next line, should we chop the word or it can be fixed to show it all in one line?

**Comment by Chizzoz** [comment]
Actually, I think we are supposed to remove "Contact Us" from the menu. Let me do that now.

**Comment by OlivierJM** [comment]
> Actually, I think we are supposed to remove "Contact Us" from the menu. Let me do that now.

Ohhhh my goodness how did I forget that ?

**Comment by Chizzoz** [comment]
Hehe! An oversight I guess

**Comment by OlivierJM** [comment]
> Hehe! An oversight I guess

Totally

**Comment by Chizzoz** [comment]
How is it looking now?

**Comment by Chizzoz** [comment]
Maybe "Agenda" link should also go?

**Comment by OlivierJM** [comment]
It looks great, I will merge this soon, just waiting for all the checks to pass.

**Comment by Chizzoz** [comment]
Ok!

**Pull request merged**
