### PR TITLE
Remove lock files #58

### PR DESCRIPTION
**Pull request by tumbone**
- Removed existing package-lock and yarn.lock file references in the .gitignore file and committed this change
- Deleted the package-lock and yarn.lock files from the repository
- Re-created the package-lock and yarn.lock files file references in the .gitignore file.

### CODE REVIEW

**Comment by OlivierJM** [comment]
thanks, taking a look at this right now.

**Comment by OlivierJM** [comment]
apparently all the checks are failing, I am still investigating this, I have a feeling netlify relies on either of the lock files to build

**Comment by OlivierJM** [comment]
Hi @tumbone reading from this https://www.netlify.com/docs/build-gotchas/#build-cache
It seems that a lock file might be important for caching, it could be the reason why this is failing.
#58 
I am going to close this PR and the issue referring to it.
I am sorry for not seeing this ahead of time, I will however correct it to have one

**Comment by OlivierJM** [comment]
@allcontributors please add @tumbone for code

**Comment by tumbone** [comment]
Ok cool I see. I do understand what the fix is meant to achieve but I'm actually also not too convinced we should remove them hey? Would there be difficult challenge in restricting the package manager that is used on the project?

**Comment by OlivierJM** [comment]
> Ok cool I see. I do understand what the fix is meant to achieve but I'm actually also not too convinced we should remove them hey? Would there be difficult challenge in restricting the package manager that is used on the project?

The reason why I thought removing them would be ideal, is that it package's version conflict, especially if one contributors uses one package and another uses another, npm starts to report vulnerabilities just because the version in package.json doesn't match the one in the lock file.

I wish we could restrict to which package manager to use but the fact that most of contributors are beginners it might intimidating to them.
Any ideas on this ?

**Comment by tumbone** [comment]
> I wish we could restrict to which package manager to use but the fact that most of contributors are beginners it might intimidating to them.
Any ideas on this ?
My quick thoughts here are that it feels like we are going against the grain in nullifying lock-files. We might find ourselves with more annoying problems going forward such as inconsistencies with dependencies installed locally compared to what ends up being shipped with the application.
I will try and refresh my understanding on lock files and shrink wrapping and then get back to you.

**Comment by OlivierJM** [comment]
That’s definitely true and I noticed too, here is what I have done.
1. Closed the issues related to this.
2. Removed one lock file(kept the npm one)
3. Closed the PR that added lock files to gitingore.
4. Removed yarn from instructions in the readme(for new contributors) 

After these I ran an npm audit and it all seems good. 
It was a mistake getting lock files in gitignore, what I think is bad is having both of them.

**Comment by tumbone** [comment]
Ok that absolutely makes sense, agreed that's the most ideal solution. I won't be spending anymore time on this then, thanks.

**Comment by OlivierJM** [comment]
Thanks very much for noting this.

**Pull request closed without merging**
