### PR TITLE
Add PWA Functionality

### PR DESCRIPTION
**Pull request by Chizzoz**
To be tested on production via HTTPS.
- Added PWA manifest file to public folder
- Added PWA manifest to index.html
- Changed theme color in index.html to match logo
- Added sw.js service worker with offline mode
- edited index.js to register service worker
- Removed unused Team.js from App.js
- Changed class to className in Team.js and Tickets.js
- Added rel="noopener noreferrer" to some links missing it in Partners.js

### CODE REVIEW

**Comment by malgamves** [comment]
Having a problem adding the web app to my mobile home screen, is this something that worked for you @Chizzoz ?

**Comment by Chizzoz** [comment]
> Having a problem adding the web app to my mobile home screen, is this something that worked for you @Chizzoz ?

Morning @malgamves , yeah! This is something similar to what has worked for me on other projects in production. But since I was using local server on local machine while testing, I did not test it fully. Can only see if there is anything else needed to implement after tested in production.

**Comment by Chizzoz** [comment]
@malgamves you can use PWA Builder to verify your implementation -> https://www.pwabuilder.com/

**Comment by malgamves** [comment]
Hello, @Chizzoz I ran that test and got this back
image
Could you work on those things?

Also, there seem to be a few merge conflicts.

**Comment by Chizzoz** [comment]
> Hello, @Chizzoz I ran that test and got this back
> image
> Could you work on those things?
> 
> Also, there seem to be a few merge conflicts.

Those are the changes I was pushing, except pushManager for device push notifications, that might need some database integration. Let me try and resolve the conflicts

**Comment by Chizzoz** [comment]
I have resolved the conflict issues and now up-to-date with current state of Releases branch, let me re-implement those changes.

**Comment by Chizzoz** [comment]
Now done committing PWA scripts

**Comment by Chizzoz** [comment]
Morning! Has anyone reviewed this PR?

**Comment by OlivierJM** [comment]
> Morning! Has anyone reviewed this PR?

Hi Chizzo, apologies for the late reply, I will review this and get back. Thank you

**Comment by OlivierJM** [comment]
I was just running the checks, can you share the results you got from your side when you ran a lighthouse report?
It seems like we still have a couple of issues to work on before we fully get to a proper PWA 
but there are minor, things like changing image fonts, making we display some text while loading webfonts ...
Here is the report, another weird thing I notice is that these test vary, It was at 90 then 94 when I tried again(this is not our problem)
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdeploy-preview-130--sharp-payne-066681.netlify.com%2F&tab=desktop

**Comment by Chizzoz** [comment]
> I was just running the checks, can you share the results you got from your side when you ran a lighthouse report?
> 
> It seems like we still have a couple of issues to work on before we fully get to a proper PWA
> but there are minor, things like changing image fonts, making we display some text while loading webfonts ...
> 
> Here is the report, another weird thing I notice is that these test vary, It was at 90 then 94 when I tried again(this is not our problem)
> 
> https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdeploy-preview-130--sharp-payne-066681.netlify.com%2F&tab=desktop

Morning! It would take a bit of tweaking on my side to produce an accurate Lighthouse report, in line with production.

Checked out the report you shared from Page Speed API... Yeah! The issues are quite minimal, mostly images and fonts.

I propose implementing changes, then running audit to see impact and testing PWA caching, install prompt, etc 😬

**Comment by Chizzoz** [comment]
> I think the remaining issues we need to work on are images and fonts, and also making sure that the install scripts are working as expected.

How would you propose going about with these changes, a new PR?

**Comment by OlivierJM** [comment]
> > I think the remaining issues we need to work on are images and fonts, and also making sure that the install scripts are working as expected.
> 
> How would you propose going about with these changes, a new PR?

No We don't need another PR, there was much effort put in this, we cant ignore them just like that, 
Let's finalize it to be merged.
Is the install script working from your side? or does it need to running from a proper url, meaning we have to merge it so that it runs from devcon.co.zm

**Comment by Chizzoz** [comment]
> > > I think the remaining issues we need to work on are images and fonts, and also making sure that the install scripts are working as expected.
> > 
> > 
> > How would you propose going about with these changes, a new PR?
> 
> No We don't need another PR, there was much effort put in this, we cant ignore them just like that,
> Let's finalize it to be merged.
> Is the install script working from your side? or does it need to running from a proper url, meaning we have to merge it so that it runs from devcon.co.zm

Install script will only work on proper url. Will see if I can push in those image optimisations while PR is open then. Otherwise, will create a new one to cover those if this one is closed by then.

**Comment by OlivierJM** [comment]
> > > > I think the remaining issues we need to work on are images and fonts, and also making sure that the install scripts are working as expected.
> > > 
> > > 
> > > How would you propose going about with these changes, a new PR?
> > 
> > 
> > No We don't need another PR, there was much effort put in this, we cant ignore them just like that,
> > Let's finalize it to be merged.
> > Is the install script working from your side? or does it need to running from a proper url, meaning we have to merge it so that it runs from devcon.co.zm
> 
> Install script will only work on proper url. Will see if I can push in those image optimisations while PR is open then. Otherwise, will create a new one to cover those if this one is closed by then.

Thanks so much, We are not closing this PR infact I will look into it further then merge it then we can create some other issues remaining from here.

**Comment by Chizzoz** [comment]
> > > > > I think the remaining issues we need to work on are images and fonts, and also making sure that the install scripts are working as expected.
> > > > 
> > > > 
> > > > How would you propose going about with these changes, a new PR?
> > > 
> > > 
> > > No We don't need another PR, there was much effort put in this, we cant ignore them just like that,
> > > Let's finalize it to be merged.
> > > Is the install script working from your side? or does it need to running from a proper url, meaning we have to merge it so that it runs from devcon.co.zm
> > 
> > 
> > Install script will only work on proper url. Will see if I can push in those image optimisations while PR is open then. Otherwise, will create a new one to cover those if this one is closed by then.
> 
> Thanks so much, We are not closing this PR infact I will look into it further then merge it then we can create some other issues remaining from here.

Coolness! Will push a bit more then... 👍

**Comment by Chizzoz** [comment]
> The new format should be able to help with image optimization.

Yes! Hopefully that will help clear a few checks

**Comment by OlivierJM** [comment]
Awesome, I will go ahead and merge this then we will be pushing for more optimization.

**Comment by Chizzoz** [comment]
> Awesome, I will go ahead and merge this then we will be pushing for more optimization.

Alright! Will also test once you merge

**Comment by OlivierJM** [comment]
Thank you @Chizzoz

**Comment by Chizzoz** [comment]
> Thank you @Chizzoz

Don't mention it! Was just checking out the deployment, some harmonization needs to be done with the service worker, there seem to be two at the moment, but most of the PWA tests have passed

**Pull request merged**
