### PR TITLE
improved the ticket section

### PR DESCRIPTION
**Pull request by kazashim**
improved the ticket section

### CODE REVIEW

**Comment by OlivierJM** [comment]
Hi @kazashim thanks for the awesome changes, can we have the actual values for the ticket prices
@malgamves @k9uma help us with this so that I merge this soon.

**Comment by OlivierJM** [comment]
Fonts are taking time to load I need to take a look at what is causing this.

**Comment by kazashim** [comment]
who has the actual prices of tickets and additional info to be under the tickets

**Comment by malgamves** [comment]
Have a look at [this](https://t.co/aMBxfSIhiF)

**Comment by kazashim** [comment]
alright thanks on it now? and is there any info to include under each ticket price?

**Comment by kazashim** [comment]
> Have a look at [this](https://t.co/aMBxfSIhiF)

i am unable to see the ticket pricing

**Comment by Beardless-sheik** [comment]
@kazashim check this issue #104

**Comment by kazashim** [comment]
> @kazashim check this issue #104

Thanks

**Comment by malgamves** [comment]
Hey @kazashim there seem to be merge conflicts. Could you update your fork [like this](https://gist.github.com/CristinaSolana/1885435) it should resolve most of the conflicts and get the changes from previously merged PR's.

**Comment by kazashim** [comment]
> Hey @kazashim there seem to be merge conflicts. Could you update your fork [like this](https://gist.github.com/CristinaSolana/1885435) it should resolve most of the conflicts and get the changes from previously merged PR's.

alright will do

**Comment by malgamves** [comment]
Hi @kazashim 

We're going ahead with this PR and because they're quite a few important changes to the main site, I think we should make things as clean as they should be. 

# Review

DeepinScreenshot_select-area_20190813092524
- [ ] There seems to be some extra padding on the top of the page. The "Code of Conduct" text should also be on a single line. We also need to add home to the nav bar as #117
----
DeepinScreenshot_select-area_20190813092649
- [ ] There's an unknown character on the right side of the ticket information. Also there's a variation in text size on each of the cards. The styling seems bolder in two cards. 

     You should also link the buttons to out ticket page: https://qkt.io/I3SHAd
----
DeepinScreenshot_select-area_20190813092723
- [ ] We need some padding right below the "partner with us..." text doesn't look too clean as it is now.
----
DeepinScreenshot_select-area_20190813094201
- [ ] The font at the bottom of the footer should match the rest of the site. We also need to add "Contribute" right next to the "Code of Conduct" text to link to the repo. 
----
DeepinScreenshot_select-area_20190813092557
- [ ] The seem to be some stray elements in the page. It's worth removing them and changing the background of the about section to white.
----

Please make the changes before we can merge the PR. Thanks for the contrubution

**Comment by kazashim** [comment]
> Hi @kazashim
> 
> We're going ahead with this PR and because they're quite a few important changes to the main site, I think we should make things as clean as they should be.
> 
> # Review
> DeepinScreenshot_select-area_20190813092524
> 
> * [ ]  There seems to be some extra padding on the top of the page. The "Code of Conduct" text should also be on a single line. We also need to add home to the nav bar as #117
> 
> DeepinScreenshot_select-area_20190813092649
> 
> * [ ]  There's an unknown character on the right side of the ticket information. Also there's a variation in text size on each of the cards. The styling seems bolder in two cards.
>   You should also link the buttons to out ticket page: https://qkt.io/I3SHAd
> 
> DeepinScreenshot_select-area_20190813092723
> 
> * [ ]  We need some padding right below the "partner with us..." text doesn't look too clean as it is now.
> 
> DeepinScreenshot_select-area_20190813094201
> 
> * [ ]  The font at the bottom of the footer should match the rest of the site. We also need to add "Contribute" right next to the "Code of Conduct" text to link to the repo.
> 
> DeepinScreenshot_select-area_20190813092557
> 
> * [ ]  The seem to be some stray elements in the page. It's worth removing them and changing the background of the about section to white.
> 
> Please make the changes before we can merge the PR. Thanks for the contrubution

alright on it

**Comment by OlivierJM** [comment]
Apologies for the delay, @malgamves confirm the changes, then we can resolve the conflicts and merge it.

**Comment by malgamves** [comment]
We need organising team pictures otherwise everything looks great @OlivierJM

**Comment by OlivierJM** [comment]
Maybe we can hide that section as we are still correcting them, should we create an issue where we all add links to our pics, links will be less stressful.

**Comment by malgamves** [comment]
True, lets go ahead with that then

**Pull request merged**
