### PR TITLE
PWA Tweaking

### PR DESCRIPTION
**Pull request by Chizzoz**
- Uploaded missing icon image sizes

### CODE REVIEW

**Comment by Chizzoz** [comment]
> is png better?

hehe! Probably not, those are the launcher ones though, I didn't see Lighthouse complain, so I left them. It should be best to convert them to convert them to a smaller format.

**Comment by OlivierJM** [comment]
> > is png better?
> 
> hehe! Probably not, those are the launcher ones though, I didn't see Lighthouse complain, so I left them. It should be best to convert them to a smaller format.

It looks great so far, Those don't matter much

**Comment by Chizzoz** [comment]
So, I realised what was stopping me from testing locally, in manifest.json, start_url was static = https://www.devcon.co.zm, changed that, now able to run Lighthouse locally, though not using https.

So made more changes. As it is, PWA can install on Android, screenshots below:
devconzm-pwa
In Chrome on left and launched standalone on right.

Below is Lighthouse audit on localhost, after making current changes:
devconzm localhost lighthouse

**Comment by OlivierJM** [comment]
> So, I realised what was stopping me from testing locally, in manifest.json, start_url was static = https://www.devcon.co.zm, changed that, now able to run Lighthouse locally, though not using https.
> 
> So made more changes. As it is, PWA can install on Android, screenshots below:
> devconzm-pwa
> In Chrome on left and launched standalone on right.
> 
> Below is Lighthouse audit on localhost, after making current changes:
> devconzm localhost lighthouse

Ohhhh wowww that is pretty cool, I have only been testing the live site, I didnt run lighthouse locally, but that looks awesome.

**Comment by Chizzoz** [comment]
I think the _performance_ should be better on production server

**Comment by OlivierJM** [comment]
> I think the _performance_ should be better on production server

Most definitely.

**Pull request merged**
