### PR TITLE
Adding Accessibility 

### PR DESCRIPTION
**Pull request by bgongre**
This update in in regards to the making the website semantic and having a screen reader able to read your navbar links, links on the page, and images whether being hovered over or tabbed on to.

Ref Issue: Using semantic tags correctly #81

### CODE REVIEW

**Comment by bgongre** [comment]
Created a CodeOfConduct page although it is not linked to the main page yet, it would be best to use react-router to start linking to full pages at this point. If you would like to view the code of conduct page you can replace 'App' in the index.js area with the CodeOfConduct component that is imported (I left notes in index.js as well for now). The page has all the information requested and is responsive. Let me know if you have any issues with my commits or any questions.

**Comment by malgamves** [comment]
Thank you, having a look @bgongre - Assessibilty ftw :unicorn: 

@OlivierJM we'd need the go ahead to with implementing react-router

**Comment by malgamves** [comment]
Also @bgongre a bump for the font. It's called [Keep Calm](https://www.cufonfonts.com/font/keep-calm). We can play around with using it.

**Comment by bgongre** [comment]
@malgamves Would you like to use that font for everything? Both all the text on the main page and the code of conduct page?

**Comment by OlivierJM** [comment]
@malgamves sorry for the delayed response, you have my go-ahead for the router.

**Pull request merged**
