### PR TITLE
[WIP] Change background image

### LINKED ISSUE #80: change background image
**Is your feature request related to a problem? Please describe.**
This issue is related to this #13 

**Describe the solution you'd like**
we need to change the current image background to one that properly defines Zambia
The image can be found here https://drive.google.com/drive/folders/1-qZdFJX1KzhEvGTNFcCaZ8XOUFIqOetZ

**Describe alternatives you've considered**
the alternative is to have any background that is more culture driven

**Additional context**
Though there might be some styling that needs to accompany this change you would basically need to just replace the current image with the one shared above

### PR DESCRIPTION
**Pull request by locness3**
Work-in-progress. Fixes #80

### CODE REVIEW

**Comment by locness3** [comment]
@OlivierJM Deploy still doesn't work.

**Comment by OlivierJM** [comment]
> @OlivierJM Deploy still doesn't work.

It should be fine if it is from the latest changes from the master.

Let me check this

**Comment by OlivierJM** [comment]
The build is failing because of the different in file formats, so the background.jpg can't be found because the other one is a png file.

**Comment by locness3** [comment]
Oh

**Comment by OlivierJM** [comment]
Use this image, I have reduced the side and changed the file format to make it easy when replacing.

background

**Comment by locness3** [comment]
I've pushed a new commit

**Comment by locness3** [comment]
> The build is now passing but we might need to change the font colors to match with the background

Or just move the background

**Comment by malgamves** [comment]
Awesome design and progress @locness3 
Is it possible to increase the width of the main container a little bit, it seems too centered. 
Also to sort out the image problem, we could invert it vertically and take advantage of the clouds to place our text, not sure how well it might work but its worth a shot.
The text on the site needs slight alignment too. Otherwise everything looks great!

**Comment by locness3** [comment]
> Awesome design and progress @locness3
> Is it possible to increase the width of the main container a little bit, it seems too centered.
> Also to sort out the image problem, we could invert it vertically and take advantage of the clouds to place our text, not sure how well it might work but its worth a shot.
> The text on the site needs slight alignment too. Otherwise everything looks great!

Huh, well... I din't do anything... I just changed the background... 🤔

**Comment by locness3** [comment]
@malgamves Please see my reply.

**Comment by locness3** [comment]
Please close this

**Comment by malgamves** [comment]
Hey @locness3 thank you for the contribution! Closing the issue now.

**Pull request closed without merging**
