### PR TITLE
Add partner section

### PR DESCRIPTION
**Pull request by k9uma**
Added Partners Section
Included Partners Logos: JetBrains, Agora Code Community
Added Footer Section: Including links to Code of Conduct
Commented Out: Nav Items -> Venue, Tickets, Speakers
Commented Out: Register Button

### CODE REVIEW

**Comment by k9uma** [comment]
> This looks good, we will keep the changes in the releases branch, so no merging for now.

Can we merge it into releases though?

**Comment by OlivierJM** [comment]
Ohhh Yeah I forgot it is pointing to the releases branch, yep it can be merged. 🙈

**Comment by OlivierJM** [comment]
I am merging it now.

**Comment by malgamves** [comment]
LGTM!

**Pull request merged**
