### PR TITLE
Nav links and nav link sections

### PR DESCRIPTION
**Pull request by Chizzoz**
Added sections and href nav links to the respective sections, plus some styling

### CODE REVIEW

**Comment by OlivierJM** [comment]
Thanks Chizzo, I will take a look at this tomorrow.

**Comment by Chizzoz** [comment]
Coolness :thumbsup:

**Comment by OlivierJM** [comment]
@allcontributors please add @Chizzoz for code

**Comment by OlivierJM** [comment]
Hi @Chizzoz Thanks for the contribution, and it looks really great.
Here is the link to the proposed design, we are trying to stick to that, the header looks great but the footer should look a bit different.
are you able to make some changes ?
https://drive.google.com/file/d/1qGsSnLwq9dL5DHAAUVYPe0Jkg4EwY-3o/view?usp=sharing

**Comment by OlivierJM** [comment]
Here is a live link showing the changes of your PR https://deploy-preview-40--devconzm.netlify.com/
once again thanks.

**Comment by Chizzoz** [comment]
@OlivierJM Thanks for the add and approved merge, now checking out the branding guidelines (footer included) and assets on Google drive. Will modify accordingly.

**Comment by Chizzoz** [comment]
> kindly check the requested changes.

Now checking the requested changes... Will revert...

**Comment by OlivierJM** [comment]
Heyy @Chizzoz thanks for pull request and the changes, really appreciated, I will merge it for now and I will work on the footer later.
Please note that I have added you to the list of contributors in the readme.

**Pull request merged**
