### PR TITLE
removed unwanted dependencies and updated .gitignore

### PR DESCRIPTION
**Pull request by Big-Zude**
added package-lock.json and yarn.lock in the .gitignore file

### CODE REVIEW

**Comment by OlivierJM** [comment]
what I am going to do is, I will close this PR, you can then work on a fresh one and push on a different branch to make it easy.

**Comment by OlivierJM** [comment]
before you commit try these they will help you

do `git status` to check the files that were modified 
do `git diff` to check what was modified in each file

**Comment by Big-Zude** [comment]
alright, let me do that

**Comment by OlivierJM** [comment]
awesome.

**Comment by Big-Zude** [comment]
what if i want to uncommit the changes i made,how do i go about it?

**Comment by OlivierJM** [comment]
sorry for the late reply, you can do the git checkout

so you need to know the commit id when everything was okay then you do `git checkout commitId`
the commitid is normally a long string of generated characters, but you can also do a git rest Head, look it up

**Comment by Big-Zude** [comment]
thanks for the guidance

**Pull request closed without merging**
