### PR TITLE
Nav links and nav link sections refinement

### PR DESCRIPTION
**Pull request by Chizzoz**
- Footer modification to meet prototype requirement
- Change whitesmoke color to #e6e6e6 as per prototype color palette
- Fixed background image
- Added chevron like shape before and after sections
- Removed contact us
- Increased section width
- Removed agenda section
- increased mathead minimum height

### CODE REVIEW

**Comment by Chizzoz** [comment]
Coolness! That's the issue I was trying to fix when I closed, let me see where the conflict is.

**Comment by OlivierJM** [comment]
Don't worry much about it, I can fix that first thing tomorrow morning.

**Comment by OlivierJM** [comment]
Awesome, thanks for the fix.

**Comment by Chizzoz** [comment]
Just resolved it... Welcome!

**Comment by OlivierJM** [comment]
Don't we still need the footer the one that shoes the venue ? I think it looks okay for now we can keep it there and hopefully someone else can work on it to make it look better.
Check the live demo here https://deploy-preview-50--devconzm.netlify.com/

**Comment by Chizzoz** [comment]
Alright! Yeah! I think the venue section meets more the prototype design, but we might need to replace the image currently there with the actual Grand Hotel logo

**Comment by OlivierJM** [comment]
The venue will actually be at conficius in UNZA, but we can correct that later, 

I had simply added the imports and the venue components but I think I lost the ka slick animation that was there.
check it here https://deploy-preview-50--devconzm.netlify.com/

**Comment by Chizzoz** [comment]
Ok great! Am also thinking the design looks okay on normal screen, but too stretched on a wide screen. Let me share a modification and see what you think.

**Comment by OlivierJM** [comment]
Cool, I am currently on a 13inch, but I will try and emulate a wide screen to check it out when you send the changes.

**Comment by OlivierJM** [comment]
check the also that parallax like animation that i think i lost on that last commit if you can, I had liked it 😀

**Comment by Chizzoz** [comment]
There's a screenshot of the possible option.
screencapture-localhost-3000-2019-05-18-23_18_39

**Comment by OlivierJM** [comment]
I see what you meant, It looks a bit stretched yeah.

**Comment by OlivierJM** [comment]
what you can do, is to create a new issue about this and add the screenshot above.

**Comment by Chizzoz** [comment]
Just noticed whats missing, it's the partners section. Let me add that and the other change as well, then you will decide whether to keep the slim contents section design.

**Comment by OlivierJM** [comment]
Awesome thanks.

**Comment by Chizzoz** [comment]
Pushed it through...

**Comment by OlivierJM** [comment]
@Chizzoz I will merge these changes, kindly create an issue for the bigger screen and we can get a discussion for it going there and hopefully someone can contribute to it.
I greatly appreciate for your contribution.

**Comment by Chizzoz** [comment]
Ok! Great! Let me get to raising that issue

**Pull request merged**
