### PR TITLE
added buy tickets button that redirects to the tickets page

### PR DESCRIPTION
**Pull request by geraldMaboshe**
Look forward to your: :
Look forward to your:

### CODE REVIEW

**Comment by malgamves** [comment]
Hey @geraldMaboshe could you merge #161 and #162 into one PR?

**Comment by geraldMaboshe** [comment]
> Hey @geraldMaboshe could you merge #161 and #162 into one PR?

@malgamves  how do I do that on GitHub?

**Comment by malgamves** [comment]
Have a look [here](https://stackoverflow.com/questions/14391421/merging-pull-requests-together)

**Comment by geraldMaboshe** [comment]
Cool, I will look at it a little later

**Comment by geraldMaboshe** [comment]
Hey @malgamves, it's done

**Comment by malgamves** [comment]
Hey @geraldMaboshe, just a heads up! We have a new branch `revamp` which we are concentrating all our effort on so feel free to contribute to that. 

I will be closing this PR when that is merged. Thanks for the contribution 🙏

**Comment by geraldMaboshe** [comment]
Cool

**Pull request closed without merging**
