### PR TITLE
Updated .gitignore

### PR DESCRIPTION
**Pull request by Big-Zude**
added package-lock.json and yarn.lock

### CODE REVIEW

**Comment by Big-Zude** [comment]
what are the vulnerabilities and how to do you fix them?

**Comment by OlivierJM** [comment]
vulnerabilities are caused by outdated packages and they can be fixed by either doing `npm audit fix` or update the listed packages.

**Comment by Big-Zude** [comment]
i did run npm audit fix immediately after the vulnes showed up

**Comment by OlivierJM** [comment]
> i did run npm audit fix immediately after the vulnes showed up

Did that help ?

**Comment by Big-Zude** [comment]
no, a message come up saying npm audit fix force but i did not run the force because i don't understand what the command does

**Comment by OlivierJM** [comment]
> no, a message come up saying npm audit fix force but i did not run the force because i don't understand what the command does

You did well, it is not good to force an upgrade.
the best way of fixing this is you first list the packages that are affected you can run `npm audit` then when check the package that listed ones depend on, if you want you can paste a screenshot here, so that i take a look

**Comment by Big-Zude** [comment]
image

**Pull request merged**
