### PR TITLE
Frontend changes

### PR DESCRIPTION
**Pull request by Chizzoz**
Delete Contact Us component

### CODE REVIEW

**Comment by OlivierJM** [comment]
@Chizzoz I think some packages are missing in the package.json, let me know if you can manage to fix that or if you need help

**Comment by OlivierJM** [comment]
@Chizzoz I found the issue that was making the build to error, It's fixed and your changes look great.

**Comment by Chizzoz** [comment]
Great stuff! Glad you fixed it... Was a bit tied up hehe! I noticed it was the react and react-dom version in package.json, should look out for that next time. It is coming up well, looking great 👍

**Comment by OlivierJM** [comment]
> Great stuff! Glad you fixed it... Was a bit tied up hehe! I noticed it was the react and react-dom version in package.json, should look out for that next time. It is coming up well, looking great 👍

I appreciate for the contributions, please encourage others as well to do the same.

**Comment by Chizzoz** [comment]
Don't mention it! Always a pleasure contributing... Also sharpening my skills, learning a lot in the process.

**Pull request merged**
