### PR TITLE
Responsive Header 

### PR DESCRIPTION
**Pull request by AbednegoTM**
Header is responsive at least on Dev tools mobile view. 
I created a file for mobile specific styles as well.
This is addressing issue #52

### CODE REVIEW

**Comment by AbednegoTM** [comment]
Note :  upstream came with some failing tests in InfoPage.

**Comment by OlivierJM** [comment]
Thanks Abed,  I haven't had enough time to fix the tests and I didn't write thorough tests so that is fine for now.

**Comment by OlivierJM** [comment]
@allcontributors please add @AbednegoTM for code

**Comment by AbednegoTM** [comment]
Great. So for the unused media queries I was hoping they can help someone with the  next issue I want to create. It's mobile specific. Though they can be removed on master and if someone claims the issue they can added back (as a suggestion) or new ones can be created.

**Comment by OlivierJM** [comment]
It sounds great, let's keep them there for now.

**Pull request merged**
